In [10]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [11]:
wine = load_wine()

# Convert to DataFrame
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.Series(wine.target)

print("Dataset Loaded")
print("Features Shape:", X.shape)
print("Labels Shape:", y.shape)

Dataset Loaded
Features Shape: (178, 13)
Labels Shape: (178,)


In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Train Size:", X_train.shape)
print("Test Size:", X_test.shape)

Train Size: (124, 13)
Test Size: (54, 13)


In [13]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

print("KNN Model Trained")


KNN Model Trained


In [14]:
y_pred = knn.predict(X_test)

print("Predictions Done")

Predictions Done


In [15]:
results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

results['Status'] = results.apply(
    lambda r: 'Correct' if r.Actual == r.Predicted else 'Wrong',
    axis=1
)

print("\nPrediction Results:")
print(results.head(20))


Prediction Results:
    Actual  Predicted   Status
0        0          2    Wrong
1        0          0  Correct
2        2          2  Correct
3        0          0  Correct
4        1          1  Correct
5        0          0  Correct
6        1          2    Wrong
7        2          2  Correct
8        1          1  Correct
9        2          0    Wrong
10       0          2    Wrong
11       2          2  Correct
12       0          0  Correct
13       1          1  Correct
14       0          0  Correct
15       1          1  Correct
16       1          1  Correct
17       1          1  Correct
18       0          0  Correct
19       1          1  Correct


In [16]:
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.7407407407407407

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        19
           1       0.75      0.71      0.73        21
           2       0.53      0.57      0.55        14

    accuracy                           0.74        54
   macro avg       0.73      0.73      0.73        54
weighted avg       0.74      0.74      0.74        54


Confusion Matrix:
[[17  0  2]
 [ 1 15  5]
 [ 1  5  8]]
